name: Manual Inputs
on:
  workflow_dispatch:
    inputs:

      username:
        description: 'Enter Username you want to create ScratchOrg with'
        required: true
        type: string
      validity:
        description: 'Enter for how many days ScratchOrg should be active for'
        type: integer
        required: true

jobs:
  print-tag:
    runs-on: ubuntu-latest 
    steps:
      - name: Print the input obtained from user
        run: |
          echo "username is" ${{ inputs.username }} "& ScratchOrg should be avtive for" ${{ inputs.validity }} "days"
